### ISSUE TITLE
Filter System for the Inventory (And Maketplaces)

### ISSUE THREAD

**Issue by Dafgarus** [FightRPG-DiscordBotRPG/DiscordBotRPG-Server#22]
Right now the inventory can be filtered by .inv rarity or .inv type or .inv level and so on, but what I am missing is the ability to combine those key searches for example: .inv type 1 rarity 4

It would be great to be able to use any combination of search.

Any questions, message me on Discord - Dafgarus#1111

**Comment by Roncarlos** [comment]
The filter should also work with marketplaces
